EXPECTED_TEAM_FIELDS = [
    "team",
    "games",
    "mp",
    "fg",
    "fga",
    "fg_pct",
    "fg2",
    "fg2a",
    "fg2_pct",
    "fg3",
    "fg3a",
    "fg3_pct",
    "ft",
    "fta",
    "ft_pct",
    "orb",
    "drb",
    "trb",
    "ast",
    "stl",
    "blk",
    "tov",
    "pf",
    "pts",
]

EXPECTED_ROLLING_FIELDS = {
    "team",
    "date_game",
    "time_game",
    "game_type",
    "game_location",
    "opp_name",
    "conf_abbr",
    "srs",
    "game_result",
    "pts",
    "opp_pts",
    "wins",
    "losses",
    "game_streak_result",
    "game_streak_num",
    "arena",
}

AP_TOP_25 = [
    "arizona",
    "michigan",
    "houston",
    "duke",
    "iowa-state",
    "connecticut",
    "nebraska",
    "illinois",
    "kansas",
    "michigan-state",
    "north-carolina",
    "gonzaga",
    "purdue",
    "florida",
    "virginia",
    "texas-tech",
    "st-johns-ny",
    "saint-louis",
    "vanderbilt",
    "clemson",
    "arkansas",
    "brigham-young",
    "miami-oh",
    "louisville",
    "kentucky",
]

CONFERENCE_MAP = {
    "Big Ten": 1,
    "Big 12": 2,
    "ACC": 3,
    "SEC": 4,
    "Big East": 5,
    "WCC": 6,
    "A-10": 7,
    "MAC": 8,
    "Sun Belt": 9
}