EXPECTED_TEAM_FIELDS = [
    "team",
    "games",
    "mp",
    "fg",
    "fga",
    "fg_pct",
    "fg2",
    "fg2a",
    "fg2_pct",
    "fg3",
    "fg3a",
    "fg3_pct",
    "ft",
    "fta",
    "ft_pct",
    "orb",
    "drb",
    "trb",
    "ast",
    "stl",
    "blk",
    "tov",
    "pf",
    "pts",
]

EXPECTED_ROLLING_FIELDS = {
    "team",
    "date_game",
    "time_game",
    "game_type",
    "game_location",
    "opp_name",
    "conf_abbr",
    "srs",
    "game_result",
    "pts",
    "opp_pts",
    "wins",
    "losses",
    "game_streak_result",
    "game_streak_num",
    "arena",
}

AP_TOP_25 = [
    "arizona",
    "michigan",
    "houston",
    "duke",
    "iowa-state",
    "connecticut",
    "nebraska",
    "illinois",
    "kansas",
    "michigan-state",
    "north-carolina",
    "gonzaga",
    "purdue",
    "florida",
    "virginia",
    "texas-tech",
    "st-johns-ny",
    "saint-louis",
    "vanderbilt",
    "clemson",
    "arkansas",
    "brigham-young",
    "miami-oh",
    "louisville",
    "kentucky",
]

CONFERENCE_MAP = {
    "Big Ten": 1,
    "Big 12": 2,
    "ACC": 3,
    "SEC": 4,
    "Big East": 5,
    "WCC": 6,
    "A-10": 7,
    "MAC": 8,
    "Sun Belt": 9,
}

WRONG_NAMES_MAP = {
    "nc-state": "north-carolina-state",
    "tcu": "texas-christian",
    "ucf": "central-florida",
    "st.-johns-ny": "st-johns-ny",
}

TOP_100_CURRENT = [
    "michigan",
    "duke",
    "arizona",
    "illinois",
    "iowa-state",
    "florida",
    "gonzaga",
    "houston",
    "purdue",
    "louisville",
    "michigan-state",
    "vanderbilt",
    "arkansas",
    "kansas",
    "connecticut",
    "alabama",
    "nebraska",
    "tennessee",
    "texas-tech",
    "brigham-young",
    "st-johns-ny",
    "nc-state",
    "virginia",
    "saint-louis",
    "kentucky",
    "utah-state",
    "iowa",
    "north-carolina",
    "southern-methodist",
    "georgia",
    "indiana",
    "auburn",
    "texas",
    "wisconsin",
    "ohio-state",
    "texas-am",
    "miami-fl",
    "villanova",
    "clemson",
    "saint-marys-ca",
    "santa-clara",
    "ucla",
    "washington",
    "baylor",
    "new-mexico",
    "san-diego-state",
    "tcu",
    "cincinnati",
    "ucf",
    "virginia-commonwealth",
    "louisiana-state",
    "wake-forest",
    "seton-hall",
    "virginia-tech",
    "southern-california",
    "west-virginia",
    "missouri",
    "oklahoma",
    "boise-state",
    "california",
    "oklahoma-state",
    "south-florida",
    "northwestern",
    "stanford",
    "providence",
    "arizona-state",
    "butler",
    "creighton",
    "grand-canyon",
    "tulsa",
    "syracuse",
    "colorado",
    "nevada",
    "minnesota",
    "notre-dame",
    "florida-state",
    "kansas-state",
    "mississippi-state",
    "george-washington",
    "mississippi",
    "belmont",
    "akron",
    "georgetown",
    "oregon",
    "xavier",
    "wyoming",
    "mcneese-state",
    "colorado-state",
    "wichita-state",
    "northern-iowa",
    "pittsburgh",
    "high-point",
    "marquette",
    "south-carolina",
    "dayton",
    "depaul",
    "illinois-state",
    "utah",
    "yale",
    "utah-valley",
]
